AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - '_site/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false